### ISSUE TITLE
NAGIOS is not Showing correct status of Airtel Link @ Sec 63

### ISSUE THREAD

**Issue by hariharan-isgec** [Isgec/ITIL-NAGIOS#1]
Direct Internet which is via Airtel link was not working. Nagios did not show any service as down. After manual verification it was found Airtel link at Sec 63 was down.

**@bhupender-isgec Please Investigate**

**Comment by bhupender-isgec** [comment]
Dear Sir,

 

Nagios is checking through proxy which has one route for both internet connectivity. i am trying to check through other network & that can be verified once link gets ok.

 

Thanks

Bhupender K Kashyap

**Comment by bhupender-isgec** [comment]
Dear Sir,

 

There is a configuration change required post observation. 

 

Airtel monitored through 192.168.25.149  ( Status Failed ) but showing OK in Nagios

 

Configuration line in Nagios for airtel link check in check_proxy_server_airtel_sec63.sh file

Nagios monitoring line :     output1="$(/usr/local/nagios/libexec/custom/check_squid.pl http://www.worldtimeserver.com/current_time_in_IN.aspx - - 192.168.25.149 3128 - - 2)"

                                                    Status1=$?

 

Line added in check_proxy_server_airtel_sec63.sh file 

 

output2="$(/usr/local/nagios/libexec/check_smtp -H 182.71.161.74)"

status2=$?

 

*********************************************START OF CONFIGURATION***********************************************************************

output1="$(/usr/local/nagios/libexec/custom/check_squid.pl  <http://www.worldtimeserver.com/current_time_in_IN.aspx> http://www.worldtimeserver.com/current_time_in_IN.aspx - - 192.168.25.149 3128 - - 2)"

status1=$?

output2="$(/usr/local/nagios/libexec/check_smtp -H 182.71.161.74)"

status2=$?

 

if [ "$status1" -eq "0" ] && [ "$status2" -eq "0" ]; then

        echo "Secondary Proxy Server Sec63-AirTel is Running"

        exit 0

fi

 

echo "Secondary Proxy Server Sec63-AirTel is Not Running"

exit 2

 

********************************************END OF CONFIGURATION *****************************************************************************

 

Supporting Information :

1.	Checked Barracuda through CPL is unable to connect to Airtel Barracuda device at 63 on port 25 which was not available due to internet connectivity issue but not shown in nagios.

182.71.161.74 is the barracuda 63 ip.

 

RESULT : Currently Airtel Link of 63 is monitored via sector 24 internet to airtel ip configured at our Barracuda device in 63.

 

Thanks

Bhupender K Kashyap 

 

 

 

 

 

 

From: Bhupender K Kashyap <bhupender.kashyap@isgec.co.in> 
Sent: 31 December 2020 14:45
To: 'Isgec/ITIL-NAGIOS' <reply@reply.github.com>; 'Isgec/ITIL-NAGIOS' <ITIL-NAGIOS@noreply.github.com>
Cc: 'Bhupender K Kashyap' <bhupenderkashyap@isgec.co.in>; 'Mention' <mention@noreply.github.com>
Subject: RE: [Isgec/ITIL-NAGIOS] NAGIOS is not Showing correct status of Airtel Link @ Sec 63 (#1)

 

Dear Sir,

 

Nagios is checking through proxy which has one route for both internet connectivity. i am trying to check through other network & that can be verified once link gets ok.

 

Thanks

Bhupender K Kashyap

**Comment by hariharan-isgec** [comment]
OK
